(ns yetibot.models.jargon)

(def jargon ["Going forward"
             "Drill-down"
             "End of play"
             "Touch base"
             "It's on my radar"
             "No brainer"
             "Best of breed"
             "Low hanging fruit"
             "Reach out"
             "Dive deeper"
             "Think outside the box"
             "Positive momentum"
             "On my plate"
             "At the end of the day"
             "Run the numbers"
             "Touch points"
             "Keep your eye on the ball"
             "Back to the drawing board"
             "Get the ball rolling"
             "Bang for your buck"
             "Close the deal"
             "When the rubber hits the road"
             "Shift paradigm"
             "Move the needle"
             "Game-changing"
             "Move the goal post"
             "Value added"
             "Win-win"
             "Across the piece"
             "All hands on deck"])
