(ns yetibot.models.jargon)

(def jargon ["Going forward"
             "Drill-down"
             "Double click into that"
             "In the whitespace"
             "Part of our playbook"
             "Ideation"
             "Hybrid cloud"
             "Homegrown architecture"
             "Lights out; game over"
             "Differentiation"
             "Happy path"
             "Diverge-converge"
             "End of play"
             "Touch base"
             "Disrupt the market"
             "It's on my radar"
             "No brainer"
             "Best of breed"
             "Low hanging fruit"
             "Reach out"
             "Dive deeper"
             "Think outside the box"
             "Positive momentum"
             "On my plate"
             "At the end of the day"
             "Run the numbers"
             "Touch points"
             "Flesh it out"
             "Keep your eye on the ball"
             "Back to the drawing board"
             "Get the ball rolling"
             "Bang for your buck"
             "Close the deal"
             "When the rubber hits the road"
             "Shift paradigm"
             "Move the needle"
             "Game-changing"
             "Move the goal post"
             "Value added"
             "Hyper-transparent"
             "Hyper-focused"
             "Thought leadership"
             "Perpendicular swimlanes"
             "Get some oars in the water"
             "Flywheel"
             "Win-win"
             "Across the piece"
             "All hands on deck"])
