name: Auto-merge yetibot/core bumps

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.user.login == 'yetibot-admin' &&
      startsWith(github.event.pull_request.title, 'Bump yetibot/core to')
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge
